# Note: DO NOT use quantized model or quantization_bit when merging lora adapters

# model
model_name_or_path: 01-ai/Yi-1.5-6B-Chat
adapter_name_or_path: saves/Yi-1.5-6B-Chat(mix)/lora/sft
template: yi
finetuning_type: lora

# export
export_dir: models/Yi-1.5-6B-Chat(mix)
export_size: 2
export_device: cpu
export_legacy_format: false

rope_scaling: dynamic