# Note: DO NOT use quantized model or quantization_bit when merging lora adapters

# model
model_name_or_path: Qwen/Qwen-7B
adapter_name_or_path: saves/Qwen-7B(mix)/lora/sft
template: qwen
finetuning_type: lora

# export
export_dir: models/Qwen-7B(mix)
export_size: 2
export_device: cpu
export_legacy_format: false

rope_scaling: dynamic