# Note: DO NOT use quantized model or quantization_bit when merging lora adapters

# model
model_name_or_path: google/gemma-7b
adapter_name_or_path: saves/gemma-7b(iclr)/lora/sft
template: gemma
finetuning_type: lora

# export
export_dir: models/gemma-7b(iclr)
export_size: 2
export_device: cpu
export_legacy_format: false

rope_scaling: dynamic